"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
    {
        "source": "src/generated/resources/assets/railways/lang/en_us.json",
        "translation": "src/main/resources/assets/railways/lang/%locale_with_underscore%.json",
        "languages_mapping": {
            "locale_with_underscore": {
                "de_AT": "de_at",
                "de_DE": "de_de",
                "es_ES": "es_es",
                "fr_FR": "fr_fr",
                "ja_JP": "ja_jp",
                "ko_KR": "ko_kr",
                "nl_NL": "nl_nl",
                "pl_PL": "pl_pl",
                "zh_CN": "zh_cn"
            }
        }
    }
]
