name: Build Forge Release

on:
  workflow_dispatch:
    inputs:
      mc_version:
        description: Minecraft Version
        required: true
      mod_version:
        description: Mod Version
        required: true
      create_forge_version:
        description: Create forge dependency version
        required: true

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    env:
      ITHUNDXRMAVENUSERNAME: ${{ secrets.ITHUNDXRMAVENUSERNAME }}
      ITHUNDXRMAVENPASSWORD: ${{ secrets.ITHUNDXRMAVENPASSWORD }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew :forge:build

      - name: Upload artifacts to Modrinth and Curseforge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ZzjhlDgM
          modrinth-featured: false
          modrinth-token: ${{ secrets.MODRINTHTOKEN }}

          curseforge-id: 688231
          curseforge-token: ${{ secrets.CURSEFORGETOKEN }}

          files: |
            forge/build/libs/!(*-@(dev|sources|all)).jar

          name: Steam 'n Rails ${{ github.event.inputs.mod_version }} Forge ${{ github.event.inputs.mc_version }}
          version: ${{ github.event.inputs.mod_version }}-forge-${{ github.event.inputs.mc_version }}
          version-type: release
          changelog-file: forge/recent_changelog.*

          loaders: forge
          game-versions: ${{ github.event.inputs.mc_version }}
          game-version-filter: none
          dependencies: create@${{ github.event.inputs.create_forge_version }}(required){modrinth:LNytGWDc}{curseforge:328085}
          java: 17

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail